### PR TITLE
fix: ensure array buffers are only resizable if originally so; fixes #37

### LINKED ISSUE #37: Breaking change: maxByteLength in ArrayBuffer
The current implementation converts all ArrayBuffer into resizable (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/resizable). This breaks some APIs.

> TypeError: Failed to execute 'encrypt' on 'SubtleCrypto': The provided ArrayBufferView value must not be resizable.

### PR DESCRIPTION
**Pull request by brettz9**

### CODE REVIEW

File: types/typed-arrays.js [hunk 1]
```diff
@@ -44,6 +44,7 @@ function create (TypedArray) {
             stateObj.buffers.push(buffer);
             return {
                 maxByteLength: buffer.maxByteLength,
+                resizable: buffer.resizable,
```
Comment (Jack-Works) [inline types/typed-arrays.js:47]: only resizable one has maxByteLength property, so you can only store one of them to save some space

Comment (brettz9) [reply types/typed-arrays.js:47]: Yeah, I thought about that, but figure it may be clearer even if not safer.
